DELIMITER //
CREATE TRIGGER USER_DELETE
	AFTER DELETE 			
	ON USER_MST_TB
    FOR EACH ROW			
BEGIN
	DELETE FROM USER_MST_TB
		where (OLD.USER_ID);
END
// DELIMITER ;

-- CREATE DEFINER=`aws`@`%` TRIGGER `USER_MST_TB_AFTER_DELETE` 
-- AFTER DELETE ON `USER_MST_TB`
--  FOR EACH ROW
--  BEGIN
-- DELETE FROM USER_MST_TB
-- 		where (OLD.USER_ID);
-- END

-- CREATE DEFINER=`aws`@`%` TRIGGER `USER_MST_TB_AFTER_DELETE` 
-- AFTER DELETE ON `USER_MST_TB`
--  FOR EACH ROW
--  BEGIN
-- IF OLD.USER_MST_TB != OLD.USER_DTL_TB THEN
-- 	DELETE FROM USER_MST_TB where (OLD.USER_ID);
-- 	DELETE FROM USER_DTL_TB where (OLD.USER_ID);
--     END IF;
-- END